/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ia.samuelvanie.refutation.algo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
}
