/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ia.samuelvanie.refutation.algo;
import static ia.samuelvanie.refutation.algo.Refutation.*;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.fxml.FXMLLoader;


public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("Main.fxml"));
        Scene sc = new Scene(root);
        primaryStage.setTitle("SvLOGICSOLVER");
        primaryStage.setScene(sc);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
